=begin
#CryptoGate API

#Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'cgi'

module CryptoGate
  class DefaultApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Payment lifecycle event delivered to the merchant's webhook URL
    # Signed with HMAC-SHA256 over the RAW request body. Verify by comparing `X-CryptoGate-Signature: sha256=<hex>` to `hex(hmac_sha256(webhook_secret, raw_body))` using a constant-time compare. Also sent: `X-CryptoGate-Event` (the event type) and `X-Webhook-ID` (unique delivery id — use for idempotency). 
    # @param [Hash] opts the optional parameters
    # @option opts [WebhookPayload] :webhook_payload 
    # @return [nil]
    def payment_webhook(opts = {})
      payment_webhook_with_http_info(opts)
      nil
    end

    # Payment lifecycle event delivered to the merchant&#39;s webhook URL
    # Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
    # @param [Hash] opts the optional parameters
    # @option opts [WebhookPayload] :webhook_payload 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def payment_webhook_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.payment_webhook ...'
      end
      # resource path
      local_var_path = '/paymentEvent'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'webhook_payload'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['SecretKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.payment_webhook",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#payment_webhook\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
