=begin
#CryptoGate API

#Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'cgi'

module CryptoGate
  class SystemApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # API health check
    # @param [Hash] opts the optional parameters
    # @return [GetHealth200Response]
    def get_health(opts = {})
      data, _status_code, _headers = get_health_with_http_info(opts)
      data
    end

    # API health check
    # @param [Hash] opts the optional parameters
    # @return [Array<(GetHealth200Response, Integer, Hash)>] GetHealth200Response data, response status code and response headers
    def get_health_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SystemApi.get_health ...'
      end
      # resource path
      local_var_path = '/health'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'GetHealth200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"SystemApi.get_health",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SystemApi#get_health\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Hosted-checkout redirect (browser flow, publishable key)
    # Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
    # @param pk [String] Publishable key, pk_live_… / pk_test_…
    # @param amount [String] Fiat amount (≥ 1.00 USD equivalent).
    # @param crypto [CryptoSymbol] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :link Payment-link slug for attribution.
    # @return [nil]
    def hosted_checkout_redirect(pk, amount, crypto, opts = {})
      hosted_checkout_redirect_with_http_info(pk, amount, crypto, opts)
      nil
    end

    # Hosted-checkout redirect (browser flow, publishable key)
    # Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
    # @param pk [String] Publishable key, pk_live_… / pk_test_…
    # @param amount [String] Fiat amount (≥ 1.00 USD equivalent).
    # @param crypto [CryptoSymbol] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :link Payment-link slug for attribution.
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def hosted_checkout_redirect_with_http_info(pk, amount, crypto, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SystemApi.hosted_checkout_redirect ...'
      end
      # verify the required parameter 'pk' is set
      if @api_client.config.client_side_validation && pk.nil?
        fail ArgumentError, "Missing the required parameter 'pk' when calling SystemApi.hosted_checkout_redirect"
      end
      # verify the required parameter 'amount' is set
      if @api_client.config.client_side_validation && amount.nil?
        fail ArgumentError, "Missing the required parameter 'amount' when calling SystemApi.hosted_checkout_redirect"
      end
      # verify the required parameter 'crypto' is set
      if @api_client.config.client_side_validation && crypto.nil?
        fail ArgumentError, "Missing the required parameter 'crypto' when calling SystemApi.hosted_checkout_redirect"
      end
      # resource path
      local_var_path = '/pay'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'pk'] = pk
      query_params[:'amount'] = amount
      query_params[:'crypto'] = crypto
      query_params[:'link'] = opts[:'link'] if !opts[:'link'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"SystemApi.hosted_checkout_redirect",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SystemApi#hosted_checkout_redirect\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
