=begin
#GriffNode API

#Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

# Common files
require 'griffnode/api_client'
require 'griffnode/api_error'
require 'griffnode/version'
require 'griffnode/configuration'

# Models
require 'griffnode/models/account'
require 'griffnode/models/account_limits'
require 'griffnode/models/account_plan'
require 'griffnode/models/account_usage'
require 'griffnode/models/balance'
require 'griffnode/models/create_billing_checkout_request'
require 'griffnode/models/create_detailed_transaction_request'
require 'griffnode/models/create_transaction_request'
require 'griffnode/models/crypto_symbol'
require 'griffnode/models/cryptocurrency'
require 'griffnode/models/error'
require 'griffnode/models/fiat_currency'
require 'griffnode/models/get_account200_response'
require 'griffnode/models/get_health200_response'
require 'griffnode/models/get_prices200_response'
require 'griffnode/models/get_prices200_response_data'
require 'griffnode/models/get_stats200_response'
require 'griffnode/models/get_stats200_response_data'
require 'griffnode/models/inline_object'
require 'griffnode/models/inline_object_all_of_existing_transaction'
require 'griffnode/models/invoice'
require 'griffnode/models/line_item'
require 'griffnode/models/list_balances200_response'
require 'griffnode/models/list_balances200_response_data'
require 'griffnode/models/list_cryptocurrencies200_response'
require 'griffnode/models/list_cryptocurrencies200_response_data'
require 'griffnode/models/list_invoices200_response'
require 'griffnode/models/list_invoices200_response_data'
require 'griffnode/models/list_plans200_response'
require 'griffnode/models/list_plans200_response_data'
require 'griffnode/models/list_transactions200_response'
require 'griffnode/models/list_transactions200_response_data'
require 'griffnode/models/pagination'
require 'griffnode/models/payment_split'
require 'griffnode/models/plan'
require 'griffnode/models/plan_tier'
require 'griffnode/models/transaction'
require 'griffnode/models/transaction_envelope'
require 'griffnode/models/transaction_status'
require 'griffnode/models/webhook_payload'

# APIs
require 'griffnode/api/account_api'
require 'griffnode/api/billing_api'
require 'griffnode/api/market_data_api'
require 'griffnode/api/system_api'
require 'griffnode/api/transactions_api'

module GriffNode
  class << self
    # Customize default settings for the SDK using block.
    #   GriffNode.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
