=begin
#CryptoGate API

#Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module CryptoGate
  # The canonical, curated public view of a transaction (same shape from create, get and list). Internal fields (capability tokens, client_ip, address_index, derivation/db internals) are deliberately NOT exposed. 
  class Transaction
    attr_accessor :transaction_id

    attr_accessor :status

    attr_accessor :type

    attr_accessor :crypto

    attr_accessor :deposit_address

    attr_accessor :amount_crypto

    attr_accessor :amount_fiat

    attr_accessor :amount_usd

    attr_accessor :amount_paid

    attr_accessor :amount_remaining

    attr_accessor :currency_fiat

    attr_accessor :fiat_to_usd_rate

    # USD per unit of crypto, locked at creation.
    attr_accessor :exchange_rate

    attr_accessor :confirmations_required

    attr_accessor :payment_url

    attr_accessor :order_id

    attr_accessor :customer_email

    attr_accessor :items

    # On-chain payments detected toward this transaction.
    attr_accessor :payments

    # Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
    attr_accessor :metadata

    attr_accessor :success_url

    attr_accessor :cancel_url

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :expires_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'transaction_id' => :'transaction_id',
        :'status' => :'status',
        :'type' => :'type',
        :'crypto' => :'crypto',
        :'deposit_address' => :'deposit_address',
        :'amount_crypto' => :'amount_crypto',
        :'amount_fiat' => :'amount_fiat',
        :'amount_usd' => :'amount_usd',
        :'amount_paid' => :'amount_paid',
        :'amount_remaining' => :'amount_remaining',
        :'currency_fiat' => :'currency_fiat',
        :'fiat_to_usd_rate' => :'fiat_to_usd_rate',
        :'exchange_rate' => :'exchange_rate',
        :'confirmations_required' => :'confirmations_required',
        :'payment_url' => :'payment_url',
        :'order_id' => :'order_id',
        :'customer_email' => :'customer_email',
        :'items' => :'items',
        :'payments' => :'payments',
        :'metadata' => :'metadata',
        :'success_url' => :'success_url',
        :'cancel_url' => :'cancel_url',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'expires_at' => :'expires_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'transaction_id' => :'String',
        :'status' => :'TransactionStatus',
        :'type' => :'String',
        :'crypto' => :'CryptoSymbol',
        :'deposit_address' => :'String',
        :'amount_crypto' => :'Float',
        :'amount_fiat' => :'Float',
        :'amount_usd' => :'Float',
        :'amount_paid' => :'Float',
        :'amount_remaining' => :'Float',
        :'currency_fiat' => :'FiatCurrency',
        :'fiat_to_usd_rate' => :'Float',
        :'exchange_rate' => :'Float',
        :'confirmations_required' => :'Integer',
        :'payment_url' => :'String',
        :'order_id' => :'String',
        :'customer_email' => :'String',
        :'items' => :'Array<LineItem>',
        :'payments' => :'Array<PaymentSplit>',
        :'metadata' => :'Hash<String, String>',
        :'success_url' => :'String',
        :'cancel_url' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'expires_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'order_id',
        :'customer_email',
        :'items',
        :'success_url',
        :'cancel_url',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CryptoGate::Transaction` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CryptoGate::Transaction`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'transaction_id')
        self.transaction_id = attributes[:'transaction_id']
      else
        self.transaction_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'crypto')
        self.crypto = attributes[:'crypto']
      else
        self.crypto = nil
      end

      if attributes.key?(:'deposit_address')
        self.deposit_address = attributes[:'deposit_address']
      end

      if attributes.key?(:'amount_crypto')
        self.amount_crypto = attributes[:'amount_crypto']
      end

      if attributes.key?(:'amount_fiat')
        self.amount_fiat = attributes[:'amount_fiat']
      else
        self.amount_fiat = nil
      end

      if attributes.key?(:'amount_usd')
        self.amount_usd = attributes[:'amount_usd']
      else
        self.amount_usd = nil
      end

      if attributes.key?(:'amount_paid')
        self.amount_paid = attributes[:'amount_paid']
      end

      if attributes.key?(:'amount_remaining')
        self.amount_remaining = attributes[:'amount_remaining']
      end

      if attributes.key?(:'currency_fiat')
        self.currency_fiat = attributes[:'currency_fiat']
      else
        self.currency_fiat = 'USD'
      end

      if attributes.key?(:'fiat_to_usd_rate')
        self.fiat_to_usd_rate = attributes[:'fiat_to_usd_rate']
      end

      if attributes.key?(:'exchange_rate')
        self.exchange_rate = attributes[:'exchange_rate']
      end

      if attributes.key?(:'confirmations_required')
        self.confirmations_required = attributes[:'confirmations_required']
      end

      if attributes.key?(:'payment_url')
        self.payment_url = attributes[:'payment_url']
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.key?(:'items')
        if (value = attributes[:'items']).is_a?(Array)
          self.items = value
        end
      end

      if attributes.key?(:'payments')
        if (value = attributes[:'payments']).is_a?(Array)
          self.payments = value
        end
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'success_url')
        self.success_url = attributes[:'success_url']
      end

      if attributes.key?(:'cancel_url')
        self.cancel_url = attributes[:'cancel_url']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'expires_at')
        self.expires_at = attributes[:'expires_at']
      else
        self.expires_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @transaction_id.nil?
        invalid_properties.push('invalid value for "transaction_id", transaction_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @crypto.nil?
        invalid_properties.push('invalid value for "crypto", crypto cannot be nil.')
      end

      if @amount_fiat.nil?
        invalid_properties.push('invalid value for "amount_fiat", amount_fiat cannot be nil.')
      end

      if @amount_usd.nil?
        invalid_properties.push('invalid value for "amount_usd", amount_usd cannot be nil.')
      end

      if @currency_fiat.nil?
        invalid_properties.push('invalid value for "currency_fiat", currency_fiat cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @expires_at.nil?
        invalid_properties.push('invalid value for "expires_at", expires_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @transaction_id.nil?
      return false if @status.nil?
      type_validator = EnumAttributeValidator.new('String', ["basic", "detailed"])
      return false unless type_validator.valid?(@type)
      return false if @crypto.nil?
      return false if @amount_fiat.nil?
      return false if @amount_usd.nil?
      return false if @currency_fiat.nil?
      return false if @created_at.nil?
      return false if @expires_at.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["basic", "detailed"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          transaction_id == o.transaction_id &&
          status == o.status &&
          type == o.type &&
          crypto == o.crypto &&
          deposit_address == o.deposit_address &&
          amount_crypto == o.amount_crypto &&
          amount_fiat == o.amount_fiat &&
          amount_usd == o.amount_usd &&
          amount_paid == o.amount_paid &&
          amount_remaining == o.amount_remaining &&
          currency_fiat == o.currency_fiat &&
          fiat_to_usd_rate == o.fiat_to_usd_rate &&
          exchange_rate == o.exchange_rate &&
          confirmations_required == o.confirmations_required &&
          payment_url == o.payment_url &&
          order_id == o.order_id &&
          customer_email == o.customer_email &&
          items == o.items &&
          payments == o.payments &&
          metadata == o.metadata &&
          success_url == o.success_url &&
          cancel_url == o.cancel_url &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          expires_at == o.expires_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [transaction_id, status, type, crypto, deposit_address, amount_crypto, amount_fiat, amount_usd, amount_paid, amount_remaining, currency_fiat, fiat_to_usd_rate, exchange_rate, confirmations_required, payment_url, order_id, customer_email, items, payments, metadata, success_url, cancel_url, created_at, updated_at, expires_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CryptoGate.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
